# Generated by Django 5.1.7 on 2025-03-17 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogpage_isfeatured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='IsFeatured',
            field=models.BooleanField(default=False, verbose_name='Article en vedette'),
        ),
    ]
