# Generated by Django 5.1.7 on 2025-03-18 20:51

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_blogpage_body_remove_blogpage_intro_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='body2',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='intro2',
        ),
        migrations.AddField(
            model_name='blogpage',
            name='body',
            field=wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('code', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'full title'}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.blocks.TextBlock', (), {})}),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='intro',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
