# Generated by Django 5.1.7 on 2025-03-21 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_author_url_author_view_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='tags',
        ),
        migrations.DeleteModel(
            name='BlogPageTag',
        ),
    ]
