# Generated by Django 5.1.7 on 2025-03-21 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_tag_blogpage_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
