# Generated by Django 5.1.7 on 2025-03-21 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_customtag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomTag',
        ),
    ]
