# Generated by Django 5.1.7 on 2025-03-17 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_homepage_intro_homepage_splash'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='splash',
            new_name='intro',
        ),
    ]
